[package]
name = "rsa"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rug = "1.13"
rand = "0.8.0"

[lib]
name = "rsa"
path = "src/rsa/lib.rs"
